services:
  postgres:
    image: postgres:16-alpine

    container_name: eda-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eda

    ports:
      - "5441:5441"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
